# Generated by Django 4.2.9 on 2026-10-03 14:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PeriodClosure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period', models.CharField(db_index=True, max_length=7, verbose_name='所属月份')),
                ('version_no', models.PositiveIntegerField(default=1, verbose_name='版本号')),
                ('status', models.CharField(choices=[('sealing', '签署中'), ('sealed', '已封账'), ('reopened', '已重开')], default='sealing', max_length=20, verbose_name='状态')),
                ('input_range', models.JSONField(default=dict, verbose_name='输入范围快照')),
                ('rules_snapshot', models.JSONField(default=dict, verbose_name='规则快照')),
                ('summary_snapshot', models.JSONField(default=dict, verbose_name='汇总摘要快照')),
                ('required_signer_ids', models.JSONField(default=list, verbose_name='应签署人ID列表')),
                ('sealed_at', models.DateTimeField(blank=True, null=True, verbose_name='封账完成时间')),
                ('reopened_at', models.DateTimeField(blank=True, null=True, verbose_name='重开时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('closed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='closed_periods', to=settings.AUTH_USER_MODEL, verbose_name='封账发起人')),
            ],
            options={
                'verbose_name': '月份封账',
                'verbose_name_plural': '月份封账',
                'db_table': 'ac_period_closure',
                'ordering': ['-period', '-version_no'],
            },
        ),
        migrations.CreateModel(
            name='ReopenRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period', models.CharField(db_index=True, max_length=7, verbose_name='所属月份')),
                ('version_no', models.PositiveIntegerField(default=1, verbose_name='申请时封账版本号')),
                ('reason', models.TextField(verbose_name='重开原因')),
                ('status', models.CharField(choices=[('pending', '待审批'), ('approved', '已批准'), ('rejected', '已拒绝')], default='pending', max_length=20, verbose_name='状态')),
                ('reply', models.TextField(blank=True, verbose_name='审批意见')),
                ('decided_at', models.DateTimeField(blank=True, null=True, verbose_name='审批时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('applicant', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reopen_requests', to=settings.AUTH_USER_MODEL, verbose_name='申请人')),
                ('approver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_reopen_requests', to=settings.AUTH_USER_MODEL, verbose_name='审批人')),
                ('closure', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reopen_requests', to='accounting.periodclosure', verbose_name='对应封账')),
            ],
            options={
                'verbose_name': '封账重开申请',
                'verbose_name_plural': '封账重开申请',
                'db_table': 'ac_reopen_request',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ClosureSignature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('signer_name', models.CharField(max_length=50, verbose_name='签署人用户名')),
                ('signed_at', models.DateTimeField(auto_now_add=True, verbose_name='签署时间')),
                ('closure', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='signatures', to='accounting.periodclosure', verbose_name='封账版本')),
                ('signer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='closure_signatures', to=settings.AUTH_USER_MODEL, verbose_name='签署人')),
            ],
            options={
                'verbose_name': '封账签署',
                'verbose_name_plural': '封账签署',
                'db_table': 'ac_closure_signature',
                'ordering': ['signed_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='reopenrequest',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'pending')), fields=('period',), name='uniq_pending_reopen_per_period'),
        ),
        migrations.AddConstraint(
            model_name='periodclosure',
            constraint=models.UniqueConstraint(fields=('period', 'version_no'), name='uniq_closure_period_version'),
        ),
        migrations.AddConstraint(
            model_name='closuresignature',
            constraint=models.UniqueConstraint(fields=('closure', 'signer'), name='uniq_signature_closure_signer'),
        ),
    ]
