# Generated by Django 4.2.9 on 2026-10-03 14:15

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockin',
            name='business_date',
            field=models.DateField(db_index=True, default=django.utils.timezone.localdate, verbose_name='业务日期'),
        ),
        migrations.AddField(
            model_name='stockin',
            name='period',
            field=models.CharField(blank=True, db_index=True, max_length=7, verbose_name='归属月份'),
        ),
        migrations.AddField(
            model_name='stockin',
            name='version_no',
            field=models.PositiveIntegerField(default=1, verbose_name='封账版本号'),
        ),
        migrations.AddField(
            model_name='stockout',
            name='business_date',
            field=models.DateField(db_index=True, default=django.utils.timezone.localdate, verbose_name='业务日期'),
        ),
        migrations.AddField(
            model_name='stockout',
            name='period',
            field=models.CharField(blank=True, db_index=True, max_length=7, verbose_name='归属月份'),
        ),
        migrations.AddField(
            model_name='stockout',
            name='version_no',
            field=models.PositiveIntegerField(default=1, verbose_name='封账版本号'),
        ),
        migrations.AlterField(
            model_name='stockin',
            name='stock_in_time',
            field=models.DateTimeField(auto_now_add=True, verbose_name='登记时间'),
        ),
        migrations.AlterField(
            model_name='stockout',
            name='stock_out_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='出库完成时间'),
        ),
    ]
