# Generated by Django 4.2.9 on 2026-10-03 12:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('warehouse', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountingPeriod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period', models.CharField(help_text='格式 YYYY-MM', max_length=7, unique=True, verbose_name='会计期间')),
                ('status', models.CharField(choices=[('open', '开放中'), ('trial', '试算中'), ('closed', '已封账')], default='open', max_length=10, verbose_name='状态')),
                ('current_version', models.PositiveIntegerField(default=1, verbose_name='当前版本号')),
                ('trial_snapshot', models.JSONField(blank=True, default=dict, verbose_name='试算快照')),
                ('tried_at', models.DateTimeField(blank=True, null=True, verbose_name='最近试算时间')),
                ('closed_at', models.DateTimeField(blank=True, null=True, verbose_name='封账时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('closed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='closed_periods', to=settings.AUTH_USER_MODEL, verbose_name='封账人')),
                ('tried_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trial_periods', to=settings.AUTH_USER_MODEL, verbose_name='试算人')),
            ],
            options={
                'verbose_name': '会计期间',
                'verbose_name_plural': '会计期间',
                'db_table': 'wh_accounting_period',
                'ordering': ['-period'],
            },
        ),
        migrations.AddField(
            model_name='stockin',
            name='business_date',
            field=models.DateField(blank=True, default=None, help_text='收发业务实际发生日期，决定所属会计期间；缺省取录入时间', null=True, verbose_name='业务日期'),
        ),
        migrations.AddField(
            model_name='stockin',
            name='period',
            field=models.CharField(blank=True, db_index=True, default='', max_length=7, verbose_name='所属期间'),
        ),
        migrations.AddField(
            model_name='stockin',
            name='version_no',
            field=models.PositiveIntegerField(default=1, verbose_name='所属版本'),
        ),
        migrations.AddField(
            model_name='stockout',
            name='business_date',
            field=models.DateField(blank=True, default=None, help_text='收发业务实际发生日期，决定所属会计期间；缺省取创建时间', null=True, verbose_name='业务日期'),
        ),
        migrations.AddField(
            model_name='stockout',
            name='period',
            field=models.CharField(blank=True, db_index=True, default='', max_length=7, verbose_name='所属期间'),
        ),
        migrations.AddField(
            model_name='stockout',
            name='version_no',
            field=models.PositiveIntegerField(default=1, verbose_name='所属版本'),
        ),
        migrations.CreateModel(
            name='ReopenRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.TextField(verbose_name='重开原因')),
                ('status', models.CharField(choices=[('pending', '待审批'), ('approved', '已通过'), ('rejected', '已拒绝')], default='pending', max_length=20, verbose_name='状态')),
                ('approve_remark', models.TextField(blank=True, verbose_name='审批意见')),
                ('reopened_version', models.PositiveIntegerField(blank=True, null=True, verbose_name='重开后版本号')),
                ('approved_at', models.DateTimeField(blank=True, null=True, verbose_name='审批时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('approver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_reopens', to=settings.AUTH_USER_MODEL, verbose_name='审批人')),
                ('period', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reopen_requests', to='warehouse.accountingperiod', verbose_name='会计期间')),
                ('requester', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reopen_requests', to=settings.AUTH_USER_MODEL, verbose_name='申请人')),
            ],
            options={
                'verbose_name': '重开审批',
                'verbose_name_plural': '重开审批',
                'db_table': 'wh_reopen_request',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PeriodAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period', models.CharField(db_index=True, max_length=7, verbose_name='会计期间')),
                ('version_no', models.PositiveIntegerField(default=1, verbose_name='发生时版本号')),
                ('action', models.CharField(choices=[('trial', '试算'), ('close', '封账'), ('reopen_request', '申请重开'), ('reopen_approve', '批准重开'), ('reopen_reject', '拒绝重开'), ('record_change', '更正期变更')], max_length=20, verbose_name='操作类型')),
                ('detail', models.JSONField(blank=True, default=dict, verbose_name='操作详情')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='操作时间')),
                ('operator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='period_audit_logs', to=settings.AUTH_USER_MODEL, verbose_name='操作人')),
            ],
            options={
                'verbose_name': '期间审计日志',
                'verbose_name_plural': '期间审计日志',
                'db_table': 'wh_period_audit_log',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PeriodVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version_no', models.PositiveIntegerField(verbose_name='版本号')),
                ('input_scope', models.JSONField(default=dict, verbose_name='输入范围')),
                ('rule', models.JSONField(default=dict, verbose_name='汇总规则')),
                ('summary', models.JSONField(default=dict, verbose_name='汇总摘要')),
                ('sealed_at', models.DateTimeField(auto_now_add=True, verbose_name='封账时间')),
                ('period', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='versions', to='warehouse.accountingperiod', verbose_name='会计期间')),
                ('sealed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sealed_versions', to=settings.AUTH_USER_MODEL, verbose_name='封账人')),
            ],
            options={
                'verbose_name': '期间版本',
                'verbose_name_plural': '期间版本',
                'db_table': 'wh_period_version',
                'ordering': ['period_id', '-version_no'],
                'unique_together': {('period', 'version_no')},
            },
        ),
    ]
